apiVersion: apps/v1
kind: Deployment
metadata:
  name: privileged-demo
  labels:
    team: platform
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privileged-demo
  template:
    metadata:
      labels:
        app: privileged-demo
        team: platform
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
